require('dotenv').config()
const createError = require('http-errors')
const express = require('express')
const cookieParser = require('cookie-parser')
const logger = require('morgan')
const usuariosRouter = require('./routes/usuariosRouter')
const produtosRouter = require('./routes/produtosRouter')
const app = express()
app.use(logger('dev'))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use(cookieParser())
app.use('/usuarios', usuariosRouter)
app.use('/produtos', produtosRouter)
app.use(function(req, res, next) { next(createError(404)) })
app.use(function(err, req, res, next) {
  res.status(err.status || 500)
  res.json({ error: err.message })
})
module.exports = app
